"""Render reproducibility reports as Markdown and JSON."""

from __future__ import annotations

import json

from .checklist import ReproducibilityReport

_VERDICT_ICON = {"PASS": "✅", "PARTIAL": "⚠️", "MISSING": "❌"}


def render_markdown(report: ReproducibilityReport) -> str:
    """Render the full report as Markdown."""
    lines: list[str] = []
    lines.append("# Reproducibility Checklist")
    lines.append("")
    if report.paper_id:
        lines.append(f"**Paper:** `{report.paper_id}`")
    if report.title:
        lines.append(f"**Title:** {report.title}")
    lines.append("")
    lines.append(f"## Score: {report.score} / {report.max_score}")
    lines.append("")
    lines.append(_score_bar(report.score))
    lines.append("")
    lines.append("## Checklist")
    lines.append("")
    lines.append("| Category | Verdict | Points | Notes |")
    lines.append("|----------|---------|--------|-------|")
    for item in report.items:
        icon = _VERDICT_ICON.get(item.verdict.value, "")
        note = item.note.replace("|", "\\|")
        lines.append(
            f"| {item.category} | {icon} {item.verdict.value} "
            f"| {item.points:g}/{item.weight} | {note} |"
        )
    lines.append("")
    lines.append("## Evidence")
    lines.append("")
    any_evidence = False
    for item in report.items:
        if not item.evidence:
            continue
        any_evidence = True
        lines.append(f"### {item.category}")
        lines.append("")
        for quote in item.evidence:
            lines.append(f"> {quote}")
            lines.append("")
    if not any_evidence:
        lines.append("_No evidence quotes extracted._")
        lines.append("")

    if report.llm_audit:
        lines.append("## LLM Audit (optional backend)")
        lines.append("")
        lines.append(f"> {report.llm_audit.get('summary', '')}")
        lines.append("")
        missing = report.llm_audit.get("missing") or []
        if missing:
            lines.append("**Missing:** " + "; ".join(missing))
            lines.append("")

    lines.append("---")
    lines.append(
        f"_Generated by reprocheck · {report.finding_count} signals extracted · "
        "heuristics are a first pass, not a substitute for reading the paper._"
    )
    lines.append("")
    return "\n".join(lines)


def _score_bar(score: int, width: int = 20) -> str:
    filled = int(round(score / 100 * width))
    return f"`[{'█' * filled}{'░' * (width - filled)}]` {score}/100"


def render_json(report: ReproducibilityReport) -> str:
    """Render the full report as pretty-printed JSON."""
    return json.dumps(report.to_dict(), indent=2, ensure_ascii=False) + "\n"
